### ISSUE TITLE
README.md - English translation

### ISSUE THREAD

**Issue by ghost** [mehmetcoskun/Instagram-Scheduler-Auto-Post#1]
Good evening, is it possible to translate the [README.md](https://github.com/mehmetcoskun/Instagram-Scheduler-Auto-Post/blob/master/README.md) into English to understand the installation steps?

**Comment by mehmetcoskun** [comment]
Yeah, of course :) i did.

**Comment by mehmetcoskun** [comment]
Yeah, of course i did
